import { jsPDF } from "jspdf";
import autoTable from 'jspdf-autotable';

export const generateDailyReport = (user, date, mealPlan, logs, steps) => {
    const doc = new jsPDF();

    // -- Header --
    doc.setFillColor(0, 210, 255); // Neon Blue header
    doc.rect(0, 0, 210, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.text("NutriBharat AI Daily Report", 20, 20);

    doc.setFontSize(12);
    doc.text(`Date: ${date}`, 20, 30);
    doc.text(`User: ${user?.name || 'Guest'}`, 150, 30);

    // -- Summary Section --
    let yPos = 55;
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(16);
    doc.text("Daily Summary", 20, yPos);

    yPos += 10;
    doc.setFontSize(12);
    const targetCals = (user.tdee || 2000) + Math.round(steps * 0.04);
    const waterIntake = logs?.water || 0;

    const summaryData = [
        ['Metric', 'Value', 'Goal', 'Status'],
        ['Steps', steps, user.dailySteps || 10000, steps >= (user.dailySteps || 10000) ? 'Goal Met' : 'In Progress'],
        ['Calories', `${targetCals} kcal`, `${user.tdee || 2000} kcal`, 'Target'],
        ['Water', `${waterIntake} L`, `${user.waterTarget || 3} L`, waterIntake >= (user.waterTarget || 3) ? 'Hydrated' : 'Drink More']
    ];

    autoTable(doc, {
        startY: yPos,
        head: [summaryData[0]],
        body: summaryData.slice(1),
        theme: 'grid',
        headStyles: { fillColor: [0, 210, 255] },
    });

    // -- Meal Plan Section --
    yPos = doc.lastAutoTable.finalY + 20;
    doc.setFontSize(16);
    doc.text("Meal Plan Details", 20, yPos);

    yPos += 10;
    const mealRows = [];
    if (mealPlan) {
        if (mealPlan.breakfast) mealRows.push(['Breakfast', mealPlan.breakfast.item, mealPlan.breakfast.calories, logs.breakfast || 'Pending']);
        if (mealPlan.lunch) mealRows.push(['Lunch', mealPlan.lunch.item, mealPlan.lunch.calories, logs.lunch || 'Pending']);
        if (mealPlan.snack) mealRows.push(['Snack', mealPlan.snack.item, mealPlan.snack.calories, logs.snack || 'Pending']);
        if (mealPlan.dinner) mealRows.push(['Dinner', mealPlan.dinner.item, mealPlan.dinner.calories, logs.dinner || 'Pending']);
    }

    autoTable(doc, {
        startY: yPos,
        head: [['Meal', 'Item', 'Calories', 'Status']],
        body: mealRows,
        theme: 'striped',
        headStyles: { fillColor: [0, 255, 157], textColor: [0, 0, 0] }, // Neon Green
    });

    // -- Footer --
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by NutriBharat AI - Your Personal Health Assistant", 105, pageHeight - 10, { align: 'center' });

    // Save
    doc.save(`NutriBharat_Report_${date}.pdf`);
};
